services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: eventdata
    ports:
      - "5432:5432"

  spring-boot-app:
    build: ./EventReservation
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/eventdata
      PRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - db
